"""内置 Hermes 插件的中文描述映射（按插件目录名 → 中文说明）。

描述原文来自各插件仓库的 manifest.json（英文）。此处仅做平台侧展示层的中文化，
不修改 Hermes 原始文件；未命中的（用户自装 git 插件）回退显示 manifest 原文。
"""

PLUGIN_DESCRIPTION_ZH = {
    "a2a-platform": "A2A（Agent-to-Agent）协议 v1.0 支持 —— 双向的 Linux 基金会开放标准，用于智能体间通信。",
    "basic": "Dashboard 认证提供方 —— 用户名/密码（无 OAuth IDP），自托管「给 Dashboard 加个密码」的提供方。",
    "browser-browser-use": "Browser Use 云端浏览器后端，支持直接 BROWSER_USE_API_KEY 或 Nous 工具网关。",
    "browser-browserbase": "Browserbase 云端浏览器后端，需要 BROWSERBASE_API_KEY + BROWSERBASE_PROJECT_ID。",
    "browser-firecrawl": "Firecrawl 云端浏览器后端，需要 FIRECRAWL_API_KEY。",
    "buzz-platform": "Buzz 网关适配器 —— 连接 Buzz 社区中继（基于 Nostr 的人机协作平台），转发消息。",
    "chronos": "Chronos —— NAS 托管的托管 cron 提供方，用于可缩放到零的托管智能体。",
    "deepinfra": "DeepInfra 图像生成后端（FLUX、Qwen-Image 等）。",
    "dingtalk-platform": "钉钉网关适配器 —— 通过 dingtalk-stream SDK 连接钉钉，转发消息。",
    "discord-platform": "Discord 网关适配器 —— 通过 discord.py 连接 Discord，转发消息。",
    "disk-cleanup": "自动追踪并清理 Hermes 会话期间产生的临时文件（测试脚本、临时输出、cron 日志）。",
    "drain": "Dashboard 认证提供方 —— 网关 drain 控制端点的非交互式共享 Bearer 密钥。",
    "email-platform": "邮件网关适配器 —— 通过 IMAP 收件、SMTP 发件，转发邮件会话。",
    "fal": "FAL.ai 图像生成后端（flux-2-klein、flux-2-pro 等）。",
    "feishu-platform": "飞书/Lark 网关适配器 —— 通过官方 lark-oapi SDK 连接飞书（国内）或 Lark（国际），转发消息。",
    "google_chat-platform": "Google Chat 网关适配器 —— 通过认证 HTTP 回调或 Cloud Pub/Sub 订阅连接。",
    "google_meet": "加入 Google Meet 会议，实时转写字幕、语音发言并跟进后续。",
    "homeassistant-platform": "Home Assistant 网关适配器 —— 订阅 HA WebSocket 事件总线，转发状态变化。",
    "irc-platform": "IRC 网关适配器 —— 连接 IRC 服务器，转发频道/私聊消息。",
    "krea": "Krea 图像生成后端（Krea 2 Large/Medium/Medium Turbo 基础模型）。",
    "langfuse": "Langfuse 可观测性 —— 追踪会话、LLM 调用与工具使用情况。",
    "line-platform": "LINE Messaging API 网关适配器 —— 通过 aiohttp webhook 接收 LINE 事件。",
    "matrix-platform": "Matrix 网关适配器 —— 通过 mautrix 连接 Matrix homeserver（可选 E2EE），转发消息。",
    "mattermost-platform": "Mattermost 网关适配器 —— 通过 v4 REST API + WebSocket 连接，转发消息。",
    "meta-ai-image-gen": "Meta Model API 图像生成后端（muse-image）。",
    "nous": "Dashboard 认证提供方 —— 对 Nous Portal 的 OAuth 2.0（授权码 + PKCE）。",
    "ntfy-platform": "ntfy 推送通知网关适配器 —— 订阅/发布 ntfy.sh 或自托管 ntfy 主题。",
    "openai": "OpenAI 图像生成后端（gpt-image-2）。",
    "openai-codex": "OpenAI 图像生成（ChatGPT/Codex OAuth，gpt-image-2）。",
    "openrouter": "OpenRouter + Nous Portal 图像生成。",
    "photon-platform": "Photon Spectrum 网关适配器 —— 通过 Photon 托管的 Spectrum 平台连接 iMessage 等。",
    "raft-platform": "Raft 网关适配器 —— 通过本地 wake-channel 桥接，以外部智能体身份连接 Raft 工作区。",
    "security-guidance": "在文件写入工具结果中附加安全警告（检测 pickle.load、eval( 等危险模式）。",
    "self-hosted": "Dashboard 认证提供方 —— 通用自托管 OpenID Connect（授权码 + PKCE，public client）。",
    "simplex-platform": "SimpleX Chat 网关适配器 —— 通过 WebSocket 连接本地 simplex-chat 守护进程，转发消息。",
    "slack-platform": "Slack 网关适配器 —— 通过 slack-bolt Socket Mode 连接，转发消息。",
    "sms-platform": "SMS 网关适配器 —— 通过 Twilio REST API + 入站 webhook 收发短信。",
    "spotify": "原生 Spotify 集成 —— 7 个工具（播放、设备、队列、搜索、歌单、专辑、音乐库）。",
    "teams-platform": "Microsoft Teams 网关适配器 —— 通过 Bot Framework 连接 Teams，转发消息。",
    "teams_pipeline": "Microsoft Teams 会议流水线插件 —— 带持久化运行时状态与 Graph 驱动的转写优先会议纪要。",
    "telegram-platform": "Telegram 网关适配器 —— 通过 python-telegram-bot 连接，转发消息。",
    "web-brave-free": "Brave Search（免费档）网络搜索，需要 BRAVE_SEARCH_API_KEY。",
    "web-ddgs": "DuckDuckGo 网络搜索（ddgs Python 包），无需 API Key。",
    "web-exa": "Exa 网络搜索与内容提取，需要 EXA_API_KEY。",
    "web-firecrawl": "Firecrawl 网络搜索 + 内容提取。",
    "web-keenable": "Keenable 网络搜索 + 页面抓取（面向 AI 应用的独立网络索引）。",
    "web-parallel": "Parallel.ai 网络搜索 + 内容提取，需要 PARALLEL_API_KEY。",
    "web-perplexity": "Perplexity Search API 网络搜索与页面摘要，需要 PERPLEXITY_API_KEY。",
    "web-searxng": "SearXNG 网络搜索 —— 免费、自托管、注重隐私的元搜索引擎，需要 SEARXNG_URL。",
    "web-tavily": "Tavily 网络搜索 + 提取，可免 Key 或设 TAVILY_API_KEY 提升限额。",
    "web-xai": "xAI 网络搜索 —— 通过 Grok 的 agentic web_search 工具搜索网络。",
    "wecom-platform": "企业微信网关适配器 —— 注册 wecom（WebSocket 智能机器人）与 wecom_callback（自建应用）。",
    "whatsapp-platform": "WhatsApp 网关适配器 —— 通过本地 Node.js 桥接（WhatsApp Web 客户端）连接，转发消息。",
    "xai": "xAI 图像生成后端（grok-imagine-image）。",
}
